const levels = [
  {
    name: "Maraudus",
    description: "The enemy is shipping a massive amount of Arcanium on a supposedly secret mission.  Your job is to lead an invasion force to overtake the enemy and to detroy all loads of the extremely dangerous element.",
    m: [
      "00000          00000",
      "0     0            0",
      "0   000 000        0",
      "0         0        0",
      "0     0            0",
      "0     00           0",
      "      0             ",
      "        0           ",
      "       00       !   ",
      "        0       B1  ",
      "                11  ",
      "                !   ",
      "                    ",
      "         0          ",
      "                    ",
      "0    00      00    0",
      "0    00      000   0",
      "0                  0",
      "0                  0",
      "00000          00000",
    ],
    units: [
      "                    ",
      "                    ",
      " r                  ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "   r              b ",
      "   r              b ",
      "   r @            b ",
      "   r              b ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      " r                  ",
      "                    ",
      "                    ",
    ],
    unitCount: [8, 4],
    coinCount: 20,
    chestCount: 5,
    fail: () => false,
    succeed: () => !bodies.some(x => x.team === "b" || x.type === "arcanium")
  },

  {
    name: "Maraudus part two",
    description: "Maraudus part two mission test",
    m: [
      "00000          00000",
      "0                  0",
      "0                  0",
      "0                  0",
      "0                  0",
      "0                  0",
      "                 !  ",
      "                    ",
      "                 $  ",
      "                    ",
      "                 B  ",
      "                    ",
      "                    ",
      "                 $  ",
      "                    ",
      "0                ! 0",
      "0                  0",
      "0                  0",
      "0                  0",
      "00000          00000",
    ],
    units: [
      "                    ",
      " r                  ",
      " r                  ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "   r                ",
      "   r                ",
      "   r @              ",
      "   r                ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      " r                  ",
      " r                  ",
      "                    ",
    ],
    unitCount: [8, 0],
    coinCount: 20,
    chestCount: 5,
    fail: () => false,
    succeed: () => !bodies.some(x => x.team === "b")
  }
]