const levels = [
  {
    name: "Maraudus",
    description: "The enemy is shipping a massive amount of Arcanium on a supposedly secret mission.  Your job is to lead an invasion force to destroy ever enemy in the area and all crates of the dengerous element.\n\nArcanium is green and has to be protected in a very thick crate.  You'll know it when you see it.  They will not appear on your radar due to the fact that they are radiation-shielded.\n\nGood luck commander, don't let us down.",
    m: [
      "                                        ",
      " 00 00000    000000000  0     0   00000 ",
      " 0           0         0     0        0 ",
      " 0       00000        0     0           ",
      " 00        0      00       0      0     ",
      "           0      00      0       00000 ",
      "00000000                 0              ",
      "             0000000    0       00000000",
      "   00000                   000          ",
      "       0      000            0          ",
      "              0    0               00   ",
      "                   0  000          0    ",
      "          00       0  0 0          0    ",
      "          00       0  000          0    ",
      "              0    0               00   ",
      "       0      000            0          ",
      "   00000                   000          ",
      "             0000000    0       00000000",
      "00000000                 0              ",
      "           0      00      0       00000 ",
      " 00        0      00       0      0     ",
      " 0       00000        0     0           ",
      " 0           0         0     0        0 ",
      " 00 00000    000000000  0     0   00000 ",
      "                                        "
    ],
    units: [
      "C                  C                   C",
      "                                        ",
      "                                        ",
      "   r r                                  ",
      "                                A       ",
      "                               b        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                     b  ",
      " r                               b      ",
      "   r                     B    b  A      ",
      "C    @                   A    A        C",
      "   r                     B    b  A      ",
      " r                               b      ",
      "                                     b  ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                               b        ",
      "                                A       ",
      "   r r                                  ",
      "                                        ",
      "                                        ",
      "C                  C                   C"
    ],
    unitCount: [8, 8],
    coinCount: 50,
    chestCount: 5,
    fail: () => false,
    succeed: () => !bodies.some(x => x.team === "b" || x.type === "arcanium")
  },

  {
    name: "Visigoth",
    description: "The enemy has managed to salvage a small amount of arcanium from the previously successful raid and have brought it into their base.  Even getting within a 100-mile radius of the enemy headquarters, we are already having turrets and heavy defenses set up.\n\nWe've located a weak spot in their defense.  Penetrate the area, destroy all enemy units and structures (including arcanium crates), and get as close as you can to the base.  We'll be in touch shortly.",
    m: [
      "                    ",
      "  0      00      0  ",
      " 000    0000    000 ",
      "  0!     00     !0  ",
      "                    ",
      "     00      00     ",
      "     00      00     ",
      "                    ",
      "         00         ",
      "  000  000000  000  ",
      "                    ",
      "                    ",
      " 00  000    000  00 ",
      " 0                0 ",
      "                    ",
      "                    ",
      "0  0000$    $0000  0",
      "0      00  00      0",
      "0                  0",
      "!                  !",
      "0                  0",
      "0                  0",
      "0                  0",
      "                    ",
      "                    ",
      "                    ",
      "00000000    00000000",
      "                    ",
      " 000000      000000 ",
      " 0    0      0    0 ",
      " 0                0 ",
      " 0                0 ",
      " 0                0 ",
      " 0    0      0    0 ",
      " 000000      000000 ",
      "                    ",
      "0                  0",
      "0                  0",
      "0                  0",
      "000000000$$000000000"
    ],
    units: [
      "   rrrrrr @ rrrrrr  ",
      "                    ",
      "                    ",
      "                    ",
      "r                  r",
      "r                  r",
      "                    ",
      "C                  C",
      "C                  C",
      "C                  C",
      "C                  C",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "  b A b      b A b  ",
      "                    ",
      "                    ",
      "                    ",
      "  b   b      b   b  ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "  b              b  ",
      "                    ",
      "    A          A    ",
      "                    ",
      "  b              b  ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    "
    ],
    unitCount: [16, 12],
    coinCount: 60,
    chestCount: 5,
    fail: () => false,
    succeed: () => !bodies.some(x => x.team === "b")
  },

  {
    name: "Vanguard",
    description: "Obviously attempting to invade an enemy base triggers a bunch of alarms, alerts, and creates a ruckus.  That, commander, is exactly what happened.  Get ready to be fighting on the open battlefront.\n\nThere will be some large access pillars around the base. Make sure those get destroyed or you won't be able to make it in.\n\nProtip: Don't forget your grenades, mines, and other powerups.  They can play a big part.",
    m: [
      "                                        ",
      " 00000000000 00000000000000 00000000000 ",
      " 0         0 0            0 0         0 ",
      " 0         0 0            0 0         0 ",
      " 0         0 0            0 0         0 ",
      " 0         0 0            0 0         0 ",
      "           0 0            0 0           ",
      "           0 0            0 0           ",
      "           0                0           ",
      "           0                0           ",
      "           0                0           ",
      "      000000                000000      ",
      "                                        ",
      "                !000000!                ",
      "                0      0                ",
      "                0      0                ",
      "0                                      0",
      "00                                    00",
      "000                                  000",
      "000              00  00              000",
      "000              00  00              000",
      "000     000      00  00      000     000",
      "000     000      00  00      000     000",
      "000     00$      00  00      $00     000",
      "000     000      00  00      000     000",
      "000     000      00  00      000     000",
      "000     000      00  00      000     000",
      "000     00!      00  00      !00     000",
      "000     000      00  00      000     000",
      "00$              00  00              $00",
      "000              00  00              000",
      "000           B1        B1           000",
      "00            11        11            00",
      "0                                      0",
      "                0 0  0 0                ",
      "            00000 0  0 00000            ",
      "       0000000000 0  0 000000000$       ",
      "    $0000000000          00000000000    ",
      "  0000000000000          0000000000000  ",
      "000000000000000          000000000000000"
    ],
    units: [
      "       r r                    r r       ",
      "                                        ",
      "                                        ",
      "       r r     r r    @ r     r r       ",
      "                                        ",
      "       r r     r r    r r     r r       ",
      "                                        ",
      "       r r     r        r     r r       ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "   b                                b   ",
      "   b                                b   ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                 bb  bb                 ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                b b b b b               ",
      "               b b b b b                "
    ],
    unitCount: [27, 18],
    coinCount: 80,
    chestCount: 10,
    fail: () => false,
    succeed: () => !bodies.some(x => x.team === "b")
  },

  {
    name: "Encapsulated",
    description: "You have successfully made it into the enemy base.  Overtake it and destroy it.  Every last enemy structure and unit must be destroyed.",
    m: [
      "0                 0     00     0                 0",
      "0                 0     00     0                 0",
      "0000000000000000000     00     0000000000000000000",
      "0000000000  0     0     00     0     0  0000000000",
      "0000000                  @                 !000000",
      "0000!                                        00000",
      "0000        0     0     00     0     0        0000",
      "00000000  0000  0000  000000  0000  0000  00000000",
      "000  0      0     0     00     0     0      0  000",
      "00   0      0     0     00     0     0      0   00",
      "00                                              $0",
      "0$                                              00",
      "0    0      0     0     00     0     0      0    0",
      "0    0      0     0    $00$    0     0      0    0",
      "00  0000  0000  0000  000000  0000  0000  0000  00",
      "0    0      0     0    $00$    0     0      0    0",
      "0    0      0     0     00     0     0      0    0",
      "0              B                  B              !",
      "!                                                0",
      "0    0      0     0     00     0     0      0    0",
      "00   0      0     0     00     0     0      0   00",
      "000  000  0000  0000  000000  0000  0000  000  000",
      "00          0     0     00     0     0          00",
      "000         0     0     00     0     0         000",
      "00$                                            000",
      "0000                 B      B                 $000",
      "00000       0     0     00     0     0       00000",
      "0000000     0     0     00     0     0     0000000",
      "0000000000  0     0     00     0     0  0000000000",
      "00000000000000000000000000000000000000000000000000"
    ],
    units: [
      "                   r   r  r   r                   ",
      "                    rrr    rrr                    ",
      "                    rrr    rrr                    ",
      "                                                  ",
      "                    rr  r@  rr                    ",
      "                    rr      rr                    ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                       b  b                       ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "       b b    b b                b b    b b       ",
      "                                                  ",
      "              b b                b b              ",
      "                                                  ",
      "                                                  "
    ],
    unitCount: [25, 14],
    coinCount: 100,
    chestCount: 15,
    fail: () => false,
    succeed: () => !bodies.some(x => x.team === "b")
  },
]